In [1]:
# Data information

# 1. variance of Wavelet Transformed image (continuous)
# 2. skewness of Wavelet Transformed image (continuous)
# 3. curtosis of Wavelet Transformed image (continuous)
# 4. entropy of image (continuous)
# 5. class (integer)

# Number of instances: 1372

In [2]:
import csv
import numpy as np

In [7]:
def load_data(path):
    
    """
    
    Loads the CSV file located at `path` into a numpy array.
    
    Args:
        path:    str path to the CSV file to be loaded
    
    Returns:
        data:    numpy array with the data arranged in 2D
        
    """

    data = np.array([])
    with open(path) as file:
        reader = csv.reader(file, delimiter=',')
        rowCnt = 0
        next(reader)
        for row in reader:
            rowCnt += 1
            for value in row:
                data = np.append(data, value)
    data = np.reshape(data, (rowCnt, -1))
    data = data.astype(np.float)
    
    return data

In [8]:
def store(path, data):
    
    """
    
    Stores `data` into persistent memory located at `path`.
    
    Args:
        path:    str path to destination
        data:    numpy array to be stored
    
    """
    
    np.save(path, data)

In [11]:
def main():
    
    data = load_data('data/housepricedata.csv')
    print(data.shape)
    store('data/data.npy', data)
    print(data)

In [12]:
main()

(1460, 11)
[[8.450e+03 7.000e+00 5.000e+00 ... 0.000e+00 5.480e+02 1.000e+00]
 [9.600e+03 6.000e+00 8.000e+00 ... 1.000e+00 4.600e+02 1.000e+00]
 [1.125e+04 7.000e+00 5.000e+00 ... 1.000e+00 6.080e+02 1.000e+00]
 ...
 [9.042e+03 7.000e+00 9.000e+00 ... 2.000e+00 2.520e+02 1.000e+00]
 [9.717e+03 5.000e+00 6.000e+00 ... 0.000e+00 2.400e+02 0.000e+00]
 [9.937e+03 5.000e+00 6.000e+00 ... 0.000e+00 2.760e+02 0.000e+00]]
